### ISSUE TITLE
[Packager] "type":"InternalError","message":"react-packager has encountered an internal error

### ISSUE THREAD

**Issue by liweijieok** [CarGuo/GSYGithubAPP#25]
你好，我运行该项目的时候发生了如下的错误。
这是 npm start的错误
```
error: bundling failed: Error: While resolving module `react-native-vector-icons/FontAwesome`, the Haste package `react-native-vector-icons` was found. However the module `FontAwesome` could not be found within the package. Indeed, none of these files exist:

  * `/Users/liweijie/dev/webstrome/GSYGithubAPP/node_modules/react-native/local-cli/core/__fixtures__/files/FontAwesome(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/Users/liweijie/dev/webstrome/GSYGithubAPP/node_modules/react-native/local-cli/core/__fixtures__/files/FontAwesome/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at resolveHasteName (/Users/liweijie/dev/webstrome/GSYGithubAPP/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:385:9)
    at ModuleResolver._resolveDependency (/Users/liweijie/dev/webstrome/GSYGithubAPP/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:315:37)
    at ModuleResolver.resolveDependency (/Users/liweijie/dev/webstrome/GSYGithubAPP/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:311:877)
    at ResolutionRequest.resolveDependency (/Users/liweijie/dev/webstrome/GSYGithubAPP/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:96:16)
    at DependencyGraph.resolveDependency (/Users/liweijie/dev/webstrome/GSYGithubAPP/node_modules/metro/src/node-haste/DependencyGraph.js:269:4352)
    at /Users/liweijie/dev/webstrome/GSYGithubAPP/node_modules/metro/src/DeltaBundler/traverseDependencies.js:201:36
    at Generator.next (<anonymous>)
    at step (/Users/liweijie/dev/webstrome/GSYGithubAPP/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:306)
    at /Users/liweijie/dev/webstrome/GSYGithubAPP/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:536
    at /Users/liweijie/dev/webstrome/GSYGithubAPP/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:217
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓░░░░░░░░░░ 42.1% (547/843), failed.

```
![8081端口错误](http://ocxgpwj6l.bkt.clouddn.com/WX20180305-172410@2x.png)

这是虚拟机的error
![虚拟机](http://ocxgpwj6l.bkt.clouddn.com/WX20180305-172329@2x.png)

相关的IP已经设置了，github的对应的token和secret也写入文件中了。
我使用的是react-native-0.52.2版本，不知道是否与之有关系。react版本是16.2.0。
您的版本是比我这个稍低。
现在情况就是一直停留在首页无法进行下一步，好像是无法拉取bundle。
初学RN，谢谢指教。

**Comment by liweijieok** [comment]
已经找到答案了：http://blog.csdn.net/klo220/article/details/79060428
