### ISSUE TITLE
run ios simulator

### ISSUE THREAD

**Issue by lhjzzu** [CarGuo/GSYGithubAPP#52]
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(The resource `/Users/liuhuajian/Downloads/GSYGithubAPP-2.0.0/node_modules/_react-native@0.57.0@react-native/index.js` was not found. (null))

__38-[RCTCxxBridge loadSource:onProgress:]_block_invoke.248
    RCTCxxBridge.mm:429
___ZL36attemptAsynchronousLoadOfBundleAtURLP5NSURLU13block_pointerFvP18RCTLoadingProgressEU13block_pointerFvP7NSErrorP9RCTSourceE_block_invoke.118
__80-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]_block_invoke
-[RCTMultipartStreamReader emitChunk:headers:callback:done:]
-[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:]
-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]
__88-[NSURLSession delegate_streamTask:didBecomeInputStream:outputStream:completionHandler:]_block_invoke
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
-[NSBlockOperation main]
-[__NSOperationInternal _start:]
__NSOQSchedule_f
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_continuation_pop
_dispatch_async_redirect_invoke
_dispatch_root_queue_drain
_dispatch_worker_thread2
_pthread_wqthread
start_wqthread

当我运行iOS模拟器是 ， 为什么会出现这样的情况?

**Comment by CarGuo** [comment]
你没有npm install吧

**Comment by lhjzzu** [comment]
我npm install了， 执行的是cnpm install

我执行 react-native run-android也是这样,终端中的错误信息是

 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)::ffff:127.0.0.1 - - [31/Oct/2018:01:52:28 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 404 - "-" "okhttp/3.10.0"
error: bundling failed: Error: The resource `/Users/liuhuajian/Downloads/GSYGithubAPP-master/node_modules/_react-native@0.57.1@react-native/index.js` was not found.

是不是因为./index.js没有bundle成功？

**Comment by CarGuo** [comment]
was not found. 看起来是不存在，你可以去node_model 找下，建议你删除了 node_model 重新执行 npm install

**Comment by lhjzzu** [comment]
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"originModulePath":"/Users/liuhuajian/Downloads/GSYGithubAPP-master/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js","targetModuleName":"schedule/tracking","message":"Unable to resolve module `schedule/tracking` from `/Users/liuhuajian/Downloads/GSYGithubAPP-master/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js`: Module `schedule/tracking` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.\n  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.","errors":[{"description":"Unable to resolve module `schedule/tracking` from `/Users/liuhuajian/Downloads/GSYGithubAPP-master/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js`: Module `schedule/tracking` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.\n  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`."}],"name":"Error","stack":"Error: Unable to resolve module `schedule/tracking` from `/Users/liuhuajian/Downloads/GSYGithubAPP-master/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js`: Module `schedule/tracking` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.\n  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.\n    at ModuleResolver.resolveDependency (/Users/liuhuajian/Downloads/GSYGithubAPP-master/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:209:1301)\n    at ResolutionRequest.resolveDependency (/Users/liuhuajian/Downloads/GSYGithubAPP-master/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:83:16)\n    at DependencyGraph.resolveDependency (/Users/liuhuajian/Downloads/GSYGithubAPP-master/node_modules/metro/src/node-haste/DependencyGraph.js:238:485)\n    at Object.resolve (/Users/liuhuajian/Downloads/GSYGithubAPP-master/node_modules/metro/src/lib/transformHelpers.js:180:25)\n    at dependencies.map.result (/Users/liuhuajian/Downloads/GSYGithubAPP-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:311:29)\n    at Array.map (<anonymous>)\n    at resolveDependencies (/Users/liuhuajian/Downloads/GSYGithubAPP-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:307:16)\n    at /Users/liuhuajian/Downloads/GSYGithubAPP-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:164:33\n    at Generator.next (<anonymous>)\n    at step (/Users/liuhuajian/Downloads/GSYGithubAPP-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:266:307)"}
processBundleResult
    BundleDownloader.java:296
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:174
execute
    RealCall.java:153
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1167
run
    ThreadPoolExecutor.java:641
run
    Thread.java:764

可能还要麻烦您一下，我执行了npm install 这次执行成功了,上次的错误没有了
 但是，然后报上面的错误，我按错误提示执行了，上面提示的步骤后依然没有任何作用
，然后我查了一些文档，都说是react-native的版本可能有问题，让降级react-native到0.55.4版本

https://blog.csdn.net/qq_38719039/article/details/80046244
https://blog.csdn.net/sinat_25017107/article/details/81359965

现在我工程中的版本如下
react-native --version
react-native-cli: 1.2.0
react-native: 0.57.1

您有什么特殊的配置吗?

**Comment by CarGuo** [comment]
没什么特殊配置，其中0.57.1针对运行问题其实官方已经修复了，你发这这个问题看起来是0.56.0那时候存在的。
你看可以看看 package.json 和 对应的 lock 文件中react 等版本是否匹配

57的官方更新log ：  https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#057

还有看下你的node版本
```
>node -v
v8.8.1
```

**Comment by CarGuo** [comment]
https://github.com/facebook/react-native/issues/21150

**Comment by lhjzzu** [comment]
非常感谢作者的耐心解答，我已经可以通过react-native run-android正常运行了。

下面我记录下，我配置环境的过程中遇到的问题，仅供别人参考。

首先环境:
react-native 0.57.1
react-native-cli 1.2.0
node  v9.10.0 【特别注意: 我遇到一个问题就是因为node版本是 v11.0.0导致，npm install时realm下载不下来，我查询的资料，说是应该用v10之前的版本】


1 在根目录npm install，我最开始使用的是cnpm install 导致各种问题，我在上面最初提问的第一个错误就是因为这个导致的，所以最好不要用。
2 配置app/config/ignoreConfig.js 
3 执行react-native run-android后，报错
The development server returned response error code: 500
Unable to resolve module schedule/tracking 【也就是上面提到的第二个错误】，

此时可以通过作者在上面的回答中提供的链接解决，即 npm install shedule@0.4.0。

4 再次运行react-android之前记得把原来的packager server关掉，然后再npm start,否则会有缓存。

5 此时再次执行react-android 即可 【当然安卓的运行环境一定要配置好】
