### ISSUE TITLE
真的很想吐槽RN

### ISSUE THREAD

**Issue by lianyagang** [CarGuo/GSYGithubAPP#92]
辣鸡啊。运行一个demo，各种跑不起来，突然间可以跑起来，然后又是漫长的等待各种错误。完全不知道怎么解决，同样是项目，flutter秒跑起来。这特码都什么鬼语言

**Comment by lianyagang** [comment]
完全不能理解，怎么会有喜欢用RN开发的，你们不觉得光这个环境都能让人吐吗

**Comment by lianyagang** [comment]
Flutter到目前为止，一次环境问题导致的无法编译都没有出现过。倒是RN，换了多少个编译器。死活就是跑不起来，突然跑起来开心了一阵子，然后什么500.什么无法安装app，我真的要吐了

**Comment by lianyagang** [comment]
得 ，跑个yarn install 各种出错，我特码开了vpn

**Comment by lianyagang** [comment]
辣鸡RN

**Comment by lianyagang** [comment]
BUILD FAILED in 5s

Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Script 'D:\RN\GSYGithubAPP\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 182

* What went wrong:
A problem occurred evaluating script.
> Text must not be null or empty

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at checkExecSyncError (child_process.js:621:11)
    at execFileSync (child_process.js:639:15)
    at runOnAllDevices (D:\RN\GSYGithubAPP\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (D:\RN\GSYGithubAPP\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at D:\RN\GSYGithubAPP\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (D:\RN\GSYGithubAPP\node_modules\@react-native-community\cli\build\index.js:164:9)
error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.

**Comment by lianyagang** [comment]
真的想吐了，写代码10分钟。编译48个小时跑不起来

**Comment by lianyagang** [comment]
不是端口占用，不是端口占用，已经重启，已经全部干掉8081端口占用的进程了。辣鸡

**Comment by lianyagang** [comment]
这是我用过的最难用的开发语言，没有之一

**Comment by CarGuo** [comment]
兄弟，加油～

**Comment by lianyagang** [comment]
flutter牛逼！！！！！

**Comment by gaodeying** [comment]
😂 刚使用RN，我已经被你们的吐槽吓到了

**Comment by CarGuo** [comment]
@gaodeying 还好还好，习惯下没什么问题的

**Comment by lianyagang** [comment]
> @gaodeying 还好还好，习惯下没什么问题的

说实话，还是Flutter亲民，作为Android原生开发，觉得Flutter简直无缝对接啊

**Comment by CarGuo** [comment]
@lianyagang 是的， flutter 对原生比较友好，rn 对前端比较友好。

那时候我第一次跑 RN 的企业项目，也是自己摸索了两天。习惯下就好了，哈哈哈哈

**Comment by zackfly** [comment]
What went wrong:
A problem occurred evaluating script.

Text must not be null or empty

**Comment by lixiaowei11111** [comment]
> > @gaodeying 还好还好，习惯下没什么问题的
> 
> 说实话，还是Flutter亲民，作为Android原生开发，觉得Flutter简直无缝对接啊

现在转Flutter了吗,RN改了挺多
